swagger: "2.0"

info:
  version: 1.0.0
  title: Authentication Services API
  description: API for handling enterprise authentication services including two-factor authentication

schemes:
  - http
host: prototypes.khill.org
basePath: /2fa

paths:
  /setup/{username}:
    get:
      summary: Sets up two-factor authentication for the given username
      description: Creates a new two-factor authentication secret for the specified username
      parameters:
        -in: path
          name: username
          schema:
            type: string
          required: true
          description: user name for setting up two-factor authentication
      responses:
        200:
          description: A boolean determining if the setup was successful
          content: 
            application/json
            schema:
              type: boolean
  /qrcode/{username}:
    get:
      summary: Retrieves the URL to display the QR code for the user 
      description: Returns a URL which will display a QR code for the user
      parameters:
        -in: path
          name: username
          schema:
            type: string
          required: true
          description: user name for the desired QR code
      responses:
        200:
          description: A URL for the qr code image
          content: 
            application/json
            schema:
              type: string
  /verify/{username}/{code}:
    get:
      summary: Verifies that the specified code is valid for the given user
      description: Checks to see if the specified 2FA code is good for this user
      parameters:
        -in: path
          name: username
          schema:
            type: string
          required: true
          description: user name for checking two-factor authentication
        -in: path
          name: code
          schema:
            type: string
          required: true
          description: code generated by authenticator app
      responses:
        200:
          description: A boolean determining if the setup was successful
          content: 
            application/json
            schema:
              type: boolean


